# Generated by Django 4.1.4 on 2022-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setofquestions",
            name="right_answers",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
